server:
  port: '8080'
  error:
    include-stacktrace: NEVER

spring:
  flyway:
    enabled: 'false'
  datasource:
    url: jdbc:mysql://localhost:3306/card_cost_db?createDatabaseIfNotExist=true&autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: mysqldocker
    hikari:
      max-lifetime: '570000'
  jpa:
    properties:
      hibernate:
        format_sql: 'true'
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    show-sql: 'true'
  sql:
    init:
      mode: always

logging:
  file:
    path: ./logs
  level:
    root: INFO


