spring:
  flyway:
    enabled: 'false'
  datasource:
    url: jdbc:mysql://localhost:3306/card_cost_db?createDatabaseIfNotExist=true&autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: mysqldocker
    hikari:
      max-lifetime: '570000'
  jpa:
    properties:
      hibernate:
        format_sql: 'false'
    show-sql: 'true'
  sql:
    init:
      mode: always
